project:
  type: website
  output-dir: docs

website:
  title: "blogs"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/BinxiePeterson
      - icon: twitter
        href: https://twitter.com/binxiepeterson?lang=en
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

